### ISSUE TITLE
Factor for terrain height extravagation 

### ISSUE THREAD

**Issue by mattrei** [blaze33/map33.js#3]
Really useful library you made here. 

May you also add a (artificial) factor for the terrain height extravagation, so that for instance when we have a higher zoom level the terrain morphology may be adjusted (via a uniform)

**Comment by blaze33** [comment]
Thanks.

Indeed there's already an hardcoded variable to multiply the elevation data:

https://github.com/blaze33/map33.js/blob/923597b3afbe965cca90686318217b0f21ba10b8/src/index.js#L215

I agree we should be able to set this value by passing an option. Though to have consistent elevation data between tiles of different zoom factors, it's the tile size that should be adjusted (ie. `size for zoom`, `size / 2 for zoom + 1`)

**Comment by blaze33** [comment]
Closed by https://github.com/blaze33/map33.js/commit/ece9d528bdb5bc1854c8d57382aa28dee93de981

You can now use:
```javascript
const zScale = 0.1 // default value is 0.045
const map = new Map(scene, camera, source, position, {zScale})
```
Let me know if that sounds good to you :)
