### ISSUE TITLE
Resolution of Geometry

### ISSUE THREAD

**Issue by mattrei** [blaze33/map33.js#4]
Currently the number of vertices of the Planebuffergeometry corresponds to the number of pixels in the raster tile heightmap. This has a bad impact on the performance, and this level of detail is generally not needed for the geometry. 
There should be a factor as an option that sets a divison factor of this (like vertices number is half of the raster image pixel size)

**Comment by blaze33** [comment]
Actually the plane number of segments is already half the size of the raster tile:

**Comment by mattrei** [comment]
yes it should be an option to greatly improve the performance. experiments show you can also have great results with a ratio of eighth of the raster size or even less.

**Comment by blaze33** [comment]
Closed by https://github.com/blaze33/map33.js/commit/ece9d528bdb5bc1854c8d57382aa28dee93de981

You can now use:
```javascript
const tileSegments = 64 // any integer value from 1 to 256!
const map = new Map(scene, camera, source, position, {tileSegments})
```
